[package]
name = "station_gen"
version = "0.1.0"
authors = ["fishykins <caspar.m.green@gmail.com>"]
edition = "2018"

[lib]
name = "station" # the name of the library that will be generated
crate-type = ["dylib"]

[dependencies]
vek = "0.12.0"
obj-rs = "0.6.1"