[station]
wings = 6
radius = 800

[wings]
modules = 3

[modules]
# Average number of rooms to generate
rooms = 20
# Width of the module as a ratio of the length
width = 0.33
# Height of the module as a ratio of the length
height = 0.33
# Area of the base mesh that is interior space
inner_space = [0.5, 0.5, 1.0] 

[rooms]
min_width = 4

[humans]
height = 2.4
width = 1.2