[package]
name = "vtor"
version = "0.1.0"
authors = ["Fishykins <caspar.m.green@gmail.com>"]
edition = "2018"

[dependencies]
prima = { path = "/home/fishy/Projects/prima" }
vek = "^0.12.0"
toml = "^0.5.6"
serde = "^1.0.1"
num = "^0.3.0"
rand = "^0.7.3"