[package]
name = "space-3d"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.6" }
bevy_rapier3d = "0.12"

[profile.dev.package.bevy]
opt-level = 3